project_id = "hywjlflrlkwgysjayozl"

[functions.book-assistant]
verify_jwt = true

[functions.nasa-space-weather]
verify_jwt = false

[functions.analyze-book-keywords]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.analyze-trending-topics]
verify_jwt = false

[functions.generate-coloring-image]
verify_jwt = false

[functions.generate-story-image]
verify_jwt = true