project_id = "hywjlflrlkwgysjayozl"

[functions.book-assistant]
verify_jwt = true

[functions.nasa-space-weather]
verify_jwt = true

[functions.analyze-book-keywords]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true